site:
  title: LabVIEW Community Training Initiative
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://labviewcommunitytraining.github.io/www/fr
  start_page: ROOT::index.adoc
  robots: allow
antora:
  extensions:
  - require: '@antora/lunr-extension'
    languages: [fr]
urls:
  latest_version_segment: latest
  latest_version_segment_strategy: redirect:to
content:
  sources:
  - url: https://github.com/LabVIEWCommunityTraining/Website-Home-Section
    branches: main
    start_paths: home_fr
  - url: https://github.com/LabVIEWCommunityTraining/Website-Course-Template
    branches: [v1.0]
    start_paths: fr
asciidoc:
  attributes:
    page-component-order: 'template'
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
    # shortcut
    lv: LabVIEW(TM)
    wip: Cette section est en cours de construction
    nt: Besoin de traduction depuis
ui:
  bundle:
    url: https://labviewcommunitytraining.github.io/Website-UI/fr/ui-bundle.zip
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
      - favicon.ico
  - path: .nojekyll
