site:
  title: LabVIEW Community Training Initiative
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://labviewcommunitytraining.github.io/www/fr
  start_page: ROOT::index.adoc
  robots: allow
antora:
  extensions:
  - require: '@antora/lunr-extension'
    languages: [fr]
  - require: ./antora-navigator-extension
    config_file: ./antora-navigator-fr.yml
  - require: '@antora/pdf-extension'
    config_file: ./antora-assembler.yml

urls:
  latest_version_segment: latest
  latest_version_segment_strategy: redirect:to
content:
  sources:
  - url: https://github.com/LabVIEWCommunityTraining/Website-Home-Section
    branches: main
    start_paths: fr
  - url: https://github.com/LabVIEWCommunityTraining/Website-Course-Template
    branches: [v*.*]
    start_paths: www/fr
  - url: https://github.com/LabVIEWCommunityTraining/cti-documentation
    branches: [v*.*]
    start_paths: www/fr
asciidoc:
  attributes:
    page-component-order: 'ROOT, course-labview, course-template'
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
    # shortcut
    lv: LabVIEW(TM)
    wip: Cette section est en cours de construction
    nt: Besoin de traduction depuis la version 
    # French translation, courtesy of Nicolas Comet <nicolas.comet@gmail.com> with updates from Maheva Bagard Laursen <mblaursen@gbif.org> --> https://github.com/asciidoctor/asciidoctor/tree/main/data/locale
    appendix-caption: Annexe
    appendix-refsig: Annexe
    caution-caption: Attention
    chapter-signifier: Chapitre
    chapter-refsig: Chapitre
    example-caption: Exemple
    figure-caption: Figure
    important-caption: Important
    last-update-label: Dernière mise à jour
    ifdef::listing-caption[:listing-caption: Liste]
    ifdef::manname-title[:manname-title: Nom]
    note-caption: Note
    part-signifier: Partie
    part-refsig: Partie
    ifdef::preface-title[:preface-title: Préface]
    section-refsig: Section
    table-caption: Tableau
    tip-caption: Astuce
    toc-title: Table des matières
    untitled-label: Sans titre
    version-label: Version
    warning-caption: Avertissement
ui:
  bundle:
    url: https://labviewcommunitytraining.github.io/Website-UI/fr/ui-bundle.zip
  supplemental_files:
  - path: partials/footer-scripts.hbs
    contents: ./supplemental-ui/partials/footer-scripts.hbs
  - path: partials/head-meta.hbs
    contents: ./supplemental-ui/partials/head-meta.hbs
  - path: partials/nav.hbs
    contents: ./supplemental-ui/partials/nav.hbs
  - path: js/nav.js
    contents: ./supplemental-ui/js/nav.js
  - path: css/nav.css
    contents: ./supplemental-ui/css/nav.css
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
      - favicon.ico
  - path: .nojekyll
